### ISSUE TITLE
CoreLocation/CLLocationManager doesn't work

### ISSUE THREAD

**Issue by jboich** [Microsoft/WinObjC#1431]
Detecting location using CLLocationManager from CoreLocation does not work: delegate methods
```
locationManager:didUpdateLocations:
locationManager:didUpdateHeading:
```
never called!

Specifying 'location' in capability requirements as mentioned here https://github.com/Microsoft/WinObjC/issues/1321  does not help.  Permission to use location by app granted in Settings. Location Services do not work neither in WOCCatalog example nor in our project.
Could you please give any advice what could be the problem and how to fix it?

Thank you in advance.

**Comment by rajsesh-msft** [comment]
@jboich What is the error you are seeing in the output window?  We regressed the woccatalog sample in the previous release, but it is fixed in #1321. You should call 
`[locationManager requestWhenInUseAuthorization];`
before making other location manager calls.  The first time the app runs, the user will get a dialog where he needs to "Allow".

**Comment by jboich** [comment]
Hi @rajsesh-msft . Thanks for your response.

> You should call
> [locationManager requestWhenInUseAuthorization];
> before making other location manager calls. The first time the app runs, the user will get a dialog where he needs to "Allow".

All of these is done, but location services still do not work if **`startUpdatingLocation `** method is used
Here are errors I see in Debug output when location manager initialized:
```
ERROR FindDefaultInterface:CM_Get_Device_Interface_List_Size failed:0x00000000, InterfaceListSize = 1 
ERROR SensorOpenByType:Failed to open sensor error:0x0000007E
```

Please follow steps to reproduce bug with location services in WOCCatalog example:

1. Uninstall WOCCatalog  app if installed
2. Start Debugging
3.  Select 'Core Location' from the list on the left hand side
4.  Click 'Yes' when alert requesting permission to use location in the app prompted.
5. Click on 'Start' (note: [locationManager startUpdatingLocation]; called)

Actual:
nothing happens

Expected:
callback received in delegate method
`- (void)locationManager:(CLLocationManager *)manager didUpdateLocations:(NSArray *)locations `
and relevant information displays in text field.

please see documentation of startUpdatingLocation() method here:
https://developer.apple.com/reference/corelocation/cllocationmanager/1423750-startupdatinglocation

Note: `[locationManager requestLocation]; ` invokes delegate method `- (void)locationManager:(CLLocationManager *)manager didUpdateLocations:(NSArray *)locations ` but only if startUpdatingLocation() hasn't been called before it.


Kind regards,
Julia

**Comment by rajsesh-msft** [comment]
thanks @jboich.

The issue here is that in [CLLocationManager](https://github.com/Microsoft/WinObjC/blob/develop/Frameworks/CoreLocation/CLLocationManager.mm#L241 ), we are looking for an older (deprecated) delegate instead of didUpdateLocations.  We are using the correct delegate for the single location request.  

Interestingly, woccatalog does not have the old delegate either, so the continuous updates probably never worked.

**Comment by jboich** [comment]
Hi, @rajsesh-msft. Thank you!
