### ISSUE TITLE
Orientation issue related to #131

### ISSUE THREAD

**Issue by volkrass** [Microsoft/WinObjC#195]
I had the same effect in my landscape oriented application like described in ticket #131. After new compilation with winobjc build 150910 the main view has been mirror inverted. Any hints how to fix?

**Comment by s5msft** [comment]
Mirror *inverted*? Not rotated? Can you share any code snippet showing how you're setting up your view?

**Comment by volkrass** [comment]
The view is rotated 180 degress around - not mirror inverted!

**Comment by volkrass** [comment]
Has been solved but not sure if it is general solution.

**Comment by Alx06** [comment]
Looks like the bug is back.
I've a "landscape" project and the screen is rotated at 180 degrees.

**Comment by bdrlamb-ms** [comment]
You can manually set/override the application startup orientation using the display settings override callback that's issued to +[UIApplication setStartupDisplayMode:] - set "mode.presentationTransform = UIInterfaceOrientationLandscapeLeft"

See "WOCDisplayMode" in /include/UIKit/UIApplication.h and "setStartupDisplayMode:" in /samples/WOCCatalog/AppDelegate.m for an example.
