### ISSUE TITLE
WOCCatalog sample fails to build with "STL1000: Unexpected compiler version, expected Clang 6 or newer."

### ISSUE THREAD

**Issue by armadsen** [Microsoft/WinObjC#2884]
Trying to build the WOCCatalog sample fails with:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		STL1000: Unexpected compiler version, expected Clang 6 or newer.	WOCCatalog (WOCCatalog\WOCCatalog)	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\include\yvals.h	297	
```

I'm using Visual Studio Community 15.7.5 with winobjc installed via Chocolatey with the --pre flag, which I believe installed `winobjc-tools 0.2.180221-dev-20180516000001`. Otherwise, I'm just following the [Quick Start Tutorial](https://github.com/Microsoft/WinObjC/wiki/Quick-Start-Tutorial).

I'd try building and installing from the latest source, but #2883 prevents that.

**Comment by edvv** [comment]
@armadsen You might want to pull files from R-51 era and work with those and then wait for a comprehensive synch with Clang 6+ related assets.

**Comment by armadsen** [comment]
Thanks Ed. Unfortunately, cloning the WinObjC repo is broken right now, so it's impossible for me to get a complete set of files to build from source, and I don't know enough about how the whole thing works to download and replace individual files.

**Comment by Liastre** [comment]
Hello @edvv can you clarify what is "R-51 era" exactly? Thanks in advice.

**Comment by edvv** [comment]
@Liastre I mean stick with a known pre-release version such as version 0.2.180220 (0.2 Preview (February 2018)) and the corresponding version of Visual Studio (Visual Studio 2017 15.4.5 or such) until Microsoft releases a unit tested release that is tested against Clang 6/7, the corresponding version of Visual Studio which ever that may be and the corresponding nuget facilities. Either that or fork/download the entire source structure and get ready for some heavy lifting.

**Comment by Liastre** [comment]
@edvv oh, got it, actually that what we doing for now, stick with 15.4.5. However, VS2017 15.4.5 recently  was removed from https://docs.microsoft.com/en-us/visualstudio/productinfo/installing-an-earlier-release-of-vs2017  and no longer available, when you guys @DHowett-MSFT gonna adapt winobjc for later release? I've actually heard v140 toolset will allow to build with, but didn't try that yet.

**Comment by Liastre** [comment]
Fixed with latest v0.2.180221 prerelease packages, you will also need [WinObjC.Compiler](https://www.nuget.org/packages/WinObjC.Compiler/0.2.180221-dev-20180516000001) package. Works with Visual Studio 15.7.X, must be fine with 15.8.X too, but I didn't test yet.

**Comment by Liastre** [comment]
Latest prerelease WinObjC packages v0.2.180221 fixes that issue, you will also need [WinObjC.Compiler](https://www.nuget.org/packages/WinObjC.Compiler/0.2.180221-dev-20180516000001) package. So far I've tested with Visual Studio 15.7.X works fine, I suppose latest 15.8.X should be fine too.

**Comment by sakrist** [comment]
It's fixed now for clang 6 error. But with VS 15.9.0 getting `expected Clang 7 or newer`.

**Comment by yistn** [comment]
Visual Studio 2017 15.9+ 
"STL1000: Unexpected compiler version, expected Clang 7 or newer."
> I'd try building and installing from the latest source, but #2883 prevents that.
please down http://releases.llvm.org/7.0.0/LLVM-7.0.0-win64.exe 
install windows set llvm PATH with system PATH (my system windows 10 1809 64bit) and rebuild OK

**Comment by marczellm** [comment]
I downloaded the LLVM release, set the LLVM Directory in project settings and I still get "expected Clang 7 or newer" error.

**Comment by edvv** [comment]
@yistn @sakrist According to this:

https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-preview

Clang/C2 is stripped out. It would be interesting to see if your noted issue went away with a VS 2019 PR.

Sincerely,

Ed

**Comment by marczellm** [comment]
On the work PC with VS2017 15.7.6, I cannot compile anything and I get the error 

> ``` clang.exe : error : unknown or ill-formed Objective-C runtime 'microsoft' ```

on every source file, even on the sample code like WOCCatalog. On my home PC I can build the samples and I have no idea what’s different between the two machines. I followed the VS install instructions as well as I could. Also Xib2Nib immediately crashes on the work PC. It works at home.

**Comment by fsb4000** [comment]
same error for me :(

**Comment by marczellm** [comment]
@DHowett-MSFT I would really appreciate some assistance with this.

**Comment by Liastre** [comment]
I've got success build and passed certification on latest VS2019 with bundled LLVM 8.0.1 from official site, using latest win SDK 10.0.18362 and v142 toolchain! You would need latest WinObjC nuget packages v0.2.180221-dev-20180516000001.

### Replace compiler
After that download official LLVM for windows from https://releases.llvm.org/download.html, then replace bin include and lib folders from packages\WinObjC.Compiler.0.2.180221-dev-20180516000001\build\LLVM to your loaded llvm.

### Edit some WinObjC sources
You would need to apply next changes to sources

packages\WinObjC.Frameworks.Core.0.2.180221-dev-20180516000001\build\include\CoreFoundation\CFPlugInCOM.h
replace `typedef unsigned int ULONG;` with `typedef unsigned long ULONG;`
replace `#define STDMETHODCALLTYPE` with `#define STDMETHODCALLTYPE __stdcall`

packages\WinObjC.Language.0.2.180221-dev-20180516000001\build\include\WOCStdLib\sys\cdefs.h
comment next fragment
```
#if !__GNUC_PREREQ__(2, 95)
#define __alignof(x) __offsetof(struct { char __a; x __b; }, __b)
#endif
```

### Update project properties
Go to your project RMB->Properties->Clang->Command Line and add `-fobjc-runtime=gnustep` then Properties->Linker->Command Line and add `/FORCE:MULTIPLE`

### Fix your source code
You possible would need to apply specific changes to your source code, for example you can't pass `lambda` with captured objective-c self object to C++ context as `std::function` you'll need to wrap those objects in `lambda` and pass in captures of another `lambda`. Also I've got some conflicts with sdk headers for sockets for example, anyway that something resolvable.

**Comment by edvv** [comment]
@Liastre That is great news! Thanks for posting it. It would be great if Microsoft (   @DHowett ) repackaged WinObjC against these latest versions (including libobjc2 r2) and updated the install readme files.
