### ISSUE TITLE
CGContextSetShadow does not work with transparency layers

### ISSUE THREAD

**Issue by adein** [Microsoft/WinObjC#584]
### Issue Description

Trying to use CGContextSetShadow with CGContext(Begin/End)TransparencyLayer does not result in a shadow.
##### Reproduction Steps
1. Enable shadows with CGContextSetShadow
2. Begin a transparency layer
3. Draw several shapes
4. End the transparency layer
##### Expected Behavior

The shapes drawn in the transparency layer should have a unified shadow, as if the shapes were one whole shape with a shadow.
##### Observed Behavior

No shadow is drawn at all.
##### Pull Request, Test Case, or Sample Code

See [this URL](https://developer.apple.com/library/mac/documentation/GraphicsImaging/Conceptual/drawingwithquartz2d/dq_trans_layers/dq_trans_layers.html) for how Apple expects it to work.

```
    CGContextRef context = UIGraphicsGetCurrentContext();
    CGFloat maxWidth = rect.size.width;
    CGFloat maxHeight = rect.size.height;

    // White background
    CGContextSetFillColorWithColor(context, [UIColor whiteColor].CGColor);
    CGContextFillRect(context, CGRectMake(0, 0, maxWidth, maxHeight));

    // Rect Size
    CGFloat rectWidth = maxWidth / 2.0;
    CGFloat rectHeight = rectWidth;

    // Enable shadow
    CGSize shadowOffset = CGSizeMake(10, 20);
    CGContextSetShadow(context, shadowOffset, 10);

    // Begin Transparency
    CGContextBeginTransparencyLayer(context, NULL);

    CGContextSetFillColorWithColor(context, [UIColor redColor].CGColor);
    CGContextFillRect(context, CGRectMake(rectWidth / 2 + 25, maxHeight / 2 - rectHeight / 2 - 50, rectWidth, rectHeight));
    CGContextSetFillColorWithColor(context, [UIColor greenColor].CGColor);
    CGContextFillRect(context, CGRectMake(rectWidth / 2 - 25, maxHeight / 2 - rectHeight / 2 + 25, rectWidth, rectHeight));
    CGContextSetFillColorWithColor(context, [UIColor blueColor].CGColor);
    CGContextFillRect(context, CGRectMake(rectWidth / 2 - 50, maxHeight / 2 - rectHeight / 2, rectWidth, rectHeight));

    // End Transparency
    CGContextEndTransparencyLayer(context);
```

**Comment by rajsesh-msft** [comment]
Fixed through #576.

**Comment by adein** [comment]
@rajsesh-msft #576 added the transparency APIs; it did not fix the issue with CGContextSetShadow.  CGContextSetShadow doesn't seem to work at all with drawing shapes, with or without using the transparency APIs.

**Comment by rajsesh-msft** [comment]
@adein thanks for the clarification.

**Comment by rajsesh-msft** [comment]
Will do this in D2D as part of the CG D2d migration effort.

**Comment by rajsesh-msft** [comment]
@DHowett-MSFT this is probably already addressed in the CGD2D branch?

**Comment by DHowett-MSFT** [comment]
This will be covered. Thanks!

**Comment by rajsesh-msft** [comment]
Will validate this with #1417
